Feedback
exlab-ecohub/ecohub-main pull request #1
Opened 2023-08-28 13:02 UTC by exlab-ecohub

Added working user and admin requests

2023-08-29 15:18 UTC, nikitabulak requested changes

2023-08-29 15:18 UTC, nikitabulak commented on src/main/java/team/exlab/ecohub/feedback/service/FeedbackServiceImpl.java
> +        String email = userRepository.findById(currentUser.getId()).orElseThrow(() -> new UserNotFoundException(String.format("User with id = %s not found", currentUser.getId()))).getEmail();
Ненужная операция. Email уже есть в currentUser

2023-08-29 15:18 UTC, nikitabulak commented on src/main/java/team/exlab/ecohub/feedback/controller/UserFeedbackController.java
> +    public EntityModel<FeedbackUserDto> createFeedback(@RequestBody FeedbackUserDto userFeedback) {
Нужна валидация ДТОшки (@Valid)

2023-08-29 15:18 UTC, nikitabulak commented on src/main/java/team/exlab/ecohub/feedback/service/FeedbackServiceImpl.java
> +        String email = currentUser.getEmail();
Используется 1 раз, можно не объявлять переменную.

2023-08-29 15:18 UTC, nikitabulak commented on src/main/java/team/exlab/ecohub/feedback/service/FeedbackServiceImpl.java
> +        Optional<Integer> userFeedbackCount = feedbackRepository.countFeedbackByEmail(email);
Что-то мне подсказывает, что count() никогда не вернет null. Метод репозитория может возвращать Integer, без Optional.

2023-08-29 15:18 UTC, nikitabulak commented on src/main/java/team/exlab/ecohub/feedback/service/FeedbackServiceImpl.java
> +        User currentUser = (User) SecurityContextHolder.getContext().getAuthentication().getPrincipal();
А откуда в контексте User, если эндпоинт, вызывающий этот метод, не требует авторизации?

2023-08-29 15:18 UTC, nikitabulak commented on src/main/java/team/exlab/ecohub/feedback/service/FeedbackServiceImpl.java
> +    public EntityModel<FeedbackUserDto> createFeedback(FeedbackUserDto userFeedback) {
Можно выделить отдельный класс NewFeedbackDto, который не будет содержать null поля

2023-08-29 15:18 UTC, nikitabulak commented on src/main/java/team/exlab/ecohub/feedback/controller/UserFeedbackController.java
> +    public EntityModel<FeedbackUserDto> getOneFeedback(@PathVariable Integer userFeedbackCount) {
One смело можно убрать из названия

2023-08-29 15:18 UTC, nikitabulak commented on src/main/java/team/exlab/ecohub/feedback/controller/AdminFeedbackController.java
> +    public AdminFeedbackController(FeedbackServiceImpl service) {
@RequiredArgsConstructor

2023-08-29 15:18 UTC, nikitabulak commented on src/main/java/team/exlab/ecohub/feedback/dto/FeedbackUserDto.java
> +    private int userFeedbackCount;
Много думал. У сущности есть id, и это поле дублирует его функционал. Соответственно это излишняя информация. Избавляясь от этого поля, получится унифицировать методы для поиска фидбэка, соединить 2 ДТО в единый FeedbackDto, сделать код понятнее

2023-08-29 15:18 UTC, nikitabulak commented on src/main/java/team/exlab/ecohub/feedback/controller/AdminFeedbackController.java
> +    @GetMapping("/messages")
а чего не feedbacks?

2023-08-29 15:18 UTC, nikitabulak commented on src/main/java/team/exlab/ecohub/feedback/controller/AdminFeedbackController.java
> +    public CollectionModel<EntityModel<FeedbackAdminDto>> getAllMessages(@RequestParam(required = false, defaultValue = "DEFAULT") String status,
status никогда не будет DEFAULT, фидбэк создается сразу со статусом OPEN

2023-08-29 15:18 UTC, nikitabulak commented on src/main/java/team/exlab/ecohub/feedback/model/ResponseStatus.java
> +import java.io.Serializable;
Ctrl + Alt + L на корневом package поможет отформатировать код и избавиться от ненужных импортов

2023-08-29 15:18 UTC, nikitabulak commented on src/main/java/team/exlab/ecohub/feedback/service/FeedbackServiceImpl.java
> +        } else if (Objects.equals(status.name(), "DEFAULT") && !Objects.equals(topic.name(), "DEFAULT")) {
status никогда не будет DEFAULT?

2023-08-29 15:18 UTC, nikitabulak commented on src/main/java/team/exlab/ecohub/feedback/dto/FeedbackUserDto.java
> +public class FeedbackUserDto {
читай ниже, объединяй с AdminDto

2023-08-29 15:18 UTC, nikitabulak commented on src/main/java/team/exlab/ecohub/feedback/dto/FeedbackAdminDto.java
> +public class FeedbackAdminDto {
смотри  FeedbackUserDto

2023-08-29 15:18 UTC, nikitabulak commented on src/main/java/team/exlab/ecohub/feedback/service/FeedbackServiceImpl.java
> +        Feedback feedback = feedbackRepository.findById(feedbackId).orElseThrow();
Ты сделал специальный эксепшн на этот случай
.orElseThrow(() -> new FeedbackNotFoundException())

2023-08-29 15:18 UTC, nikitabulak commented on src/main/java/team/exlab/ecohub/feedback/service/FeedbackServiceImpl.java
> +    public EntityModel<FeedbackAdminDto> createResponseToFeedback(FeedbackAdminDto feedbackAdminDto, Long feedbackId) {
Зачем отдельный аргумент id? Id уже есть в ДТО.

2023-08-29 15:18 UTC, nikitabulak commented on src/main/java/team/exlab/ecohub/feedback/service/FeedbackServiceImpl.java
> +        String responseContent = feedbackAdminDto.getResponseContent();
Используется 1 раз, можно не объявлять переменную.

2023-08-29 15:18 UTC, nikitabulak commented on src/main/java/team/exlab/ecohub/feedback/controller/AdminFeedbackController.java
> +    public EntityModel<FeedbackAdminDto> makeResponse(@RequestBody FeedbackAdminDto feedbackAdminDto, @PathVariable Long id) {
Нужна валидация ДТОшки (@Valid)

2023-08-29 15:18 UTC, nikitabulak commented on src/main/java/team/exlab/ecohub/feedback/dto/FeedbackAdminMapper.java
> +@Component
Зачем?

2023-08-29 15:18 UTC, nikitabulak commented on src/main/java/team/exlab/ecohub/feedback/dto/FeedbackAdminMapper.java
> +    public static Feedback toFeedback(FeedbackAdminDto feedbackAdminDto) {
не используется

2023-08-29 15:18 UTC, nikitabulak commented on src/main/java/team/exlab/ecohub/feedback/dto/FeedbackUserMapper.java
> +@Component
Зачем?

2023-08-29 15:18 UTC, nikitabulak commented on src/main/java/team/exlab/ecohub/feedback/model/Feedback.java
> +    @Column(name = "id")
при одинаковых наименованиях поля и столбца в БД аннотация не обязательна

2023-08-29 15:18 UTC, nikitabulak commented on src/main/java/team/exlab/ecohub/feedback/model/Feedback.java
> +    @Column(name = "name")
при одинаковых наименованиях поля и столбца в БД аннотация не обязательна

2023-08-29 15:18 UTC, nikitabulak commented on src/main/java/team/exlab/ecohub/feedback/model/Feedback.java
> +    @Column(name = "email")
при одинаковых наименованиях поля и столбца в БД аннотация не обязательна

2023-08-29 15:18 UTC, nikitabulak commented on src/main/java/team/exlab/ecohub/feedback/model/MessageAndResponse.java
> +//package team.exlab.ecohub.feedback;
Все-таки неиспользуемый класс лучше убрать из пул-реквеста

2023-08-29 15:18 UTC, nikitabulak commented on src/main/java/team/exlab/ecohub/feedback/model/MessageTopic.java
> +    QUESTION, OPINION, PROBLEM, ERROR, DEFAULT
Сейчас функционал не внесен в документацию, обсудим завтра на мите. Если функционала пока нет в ТЗ, следует проверить, что при создании нового фидбэка в базу будет положен DEFAULT. Потому что на данный момент, из-за неоговоренности функционала, фронт будет присылать тебе NULL

2023-08-29 15:18 UTC, nikitabulak commented on src/main/java/team/exlab/ecohub/feedback/model/ResponseStatus.java
> +    OPEN, CLOSED, IN_PROGRESS, DEFAULT
status никогда не будет DEFAULT, фидбэк создается сразу со статусом OPEN. IN_PROGRESS тоже не используется

2023-08-29 15:18 UTC, nikitabulak commented on src/main/java/team/exlab/ecohub/feedback/repository/FeedbackRepository.java
> +    Optional<Integer> countFeedbackByEmail(String email);
Скорее всего count никогда не вернет null ([стоит проверить по документации](https://docs.spring.io/spring-data/commons/docs/current/api/org/springframework/data/repository/CrudRepository.html)) -> можно отказаться от Optional

2023-08-29 15:18 UTC, nikitabulak commented on src/main/java/team/exlab/ecohub/user/model/User.java
> +//    @OneToMany(mappedBy = "user")
перед пулл-реквестом такие комменты лучше чистить

2023-08-29 15:18 UTC, nikitabulak commented on src/main/resources/schema.sql
> +    FEEDBACKS_USERS,
дублируется

2023-08-29 15:18 UTC, nikitabulak commented on src/main/resources/schema.sql
> +    FEEDBACKS,
дублируется

2023-08-29 15:18 UTC, nikitabulak commented on src/main/resources/schema.sql
> +    MESSAGES,
не используется

2023-08-29 15:18 UTC, nikitabulak commented on src/main/resources/schema.sql
> +-- insert into FEEDBACKS (user_id, user_feedback_count, name, email, message_topic, message_content, message_time, admin_id, response_content, response_time, response_status)
добавление данных в БД лучше вынести в data.sql
перед пулл-реквестом такие комменты лучше чистить

2023-08-29 15:18 UTC, nikitabulak commented on src/main/resources/schemaWithFeedback.pgerd
не используется

2023-08-29 15:18 UTC, nikitabulak commented on src/main/resources/schemaWithFeedback.sql
не используется

2023-08-29 17:50 UTC, Pvs11 commented on src/main/java/team/exlab/ecohub/feedback/service/FeedbackServiceImpl.java
> +        String email = userRepository.findById(currentUser.getId()).orElseThrow(() -> new UserNotFoundException(String.format("User with id = %s not found", currentUser.getId()))).getEmail();
fixed

2023-08-29 17:53 UTC, Pvs11 commented on src/main/resources/schemaWithFeedback.sql
removed

2023-08-29 17:53 UTC, Pvs11 commented on src/main/resources/schemaWithFeedback.pgerd
removed

2023-08-29 18:07 UTC, Pvs11 commented on src/main/resources/schema.sql
> +-- insert into FEEDBACKS (user_id, user_feedback_count, name, email, message_topic, message_content, message_time, admin_id, response_content, response_time, response_status)
fixed

2023-08-29 18:09 UTC, Pvs11 commented on src/main/resources/schema.sql
> +    MESSAGES,
fixed

2023-08-29 18:09 UTC, Pvs11 commented on src/main/resources/schema.sql
> +    FEEDBACKS,
fixed

2023-08-29 18:11 UTC, Pvs11 commented on src/main/java/team/exlab/ecohub/user/model/User.java
> +//    @OneToMany(mappedBy = "user")
fixed

2023-08-29 18:27 UTC, Pvs11 commented on src/main/java/team/exlab/ecohub/feedback/repository/FeedbackRepository.java
> +    Optional<Integer> countFeedbackByEmail(String email);
так и есть,
исправлено

2023-08-29 18:35 UTC, Pvs11 commented on src/main/java/team/exlab/ecohub/feedback/model/MessageTopic.java
> +    QUESTION, OPINION, PROBLEM, ERROR, DEFAULT
Да, ок. Если темы из предложенных вариантов приходить не будет могу ведь добавить @RequestParam и указать дефолтное значение?

2023-08-29 18:35 UTC, Pvs11 commented on src/main/java/team/exlab/ecohub/feedback/model/MessageAndResponse.java
> +//package team.exlab.ecohub.feedback;
fixed

2023-08-29 18:37 UTC, Pvs11 commented on src/main/java/team/exlab/ecohub/feedback/model/Feedback.java
> +    @Column(name = "email")
Сегодня об этом только узнал) Но считаю лучше оставить так, единообразно, для лучшей читаемости

2023-08-29 18:38 UTC, Pvs11 commented on src/main/java/team/exlab/ecohub/feedback/model/Feedback.java
> +    @Column(name = "name")
Считаю лучше оставить для наглядности

2023-08-29 18:40 UTC, Pvs11 commented on src/main/java/team/exlab/ecohub/feedback/dto/FeedbackUserMapper.java
> +@Component
fixed

2023-08-29 18:40 UTC, Pvs11 commented on src/main/java/team/exlab/ecohub/feedback/dto/FeedbackAdminMapper.java
> +    public static Feedback toFeedback(FeedbackAdminDto feedbackAdminDto) {
fixed

2023-08-29 18:42 UTC, Pvs11 commented on src/main/java/team/exlab/ecohub/feedback/dto/FeedbackAdminMapper.java
> +@Component
fixed

2023-08-30 19:08 UTC, Pvs11 commented on src/main/java/team/exlab/ecohub/feedback/controller/UserFeedbackController.java
> +    public EntityModel<FeedbackUserDto> createFeedback(@RequestBody FeedbackUserDto userFeedback) {
fixed

2023-08-30 19:09 UTC, Pvs11 commented on src/main/java/team/exlab/ecohub/feedback/service/FeedbackServiceImpl.java
> +        String email = currentUser.getEmail();
fixed

2023-08-30 19:09 UTC, Pvs11 commented on src/main/java/team/exlab/ecohub/feedback/service/FeedbackServiceImpl.java
> +        Optional<Integer> userFeedbackCount = feedbackRepository.countFeedbackByEmail(email);
fixed

2023-08-30 19:16 UTC, Pvs11 commented on src/main/java/team/exlab/ecohub/feedback/service/FeedbackServiceImpl.java
> +        User currentUser = (User) SecurityContextHolder.getContext().getAuthentication().getPrincipal();
Исправил без User из контекста, но теперь имею дело с ошибкой выбрасываемой jsonwebtoken.security: JWT signature does not match locally computed signature. JWT validity cannot be asserted and should not be trusted.
Приложение работает, но надо наверно как-то обработать этот момент.

2023-08-30 19:17 UTC, Pvs11 commented on src/main/java/team/exlab/ecohub/feedback/controller/UserFeedbackController.java
> +    public EntityModel<FeedbackUserDto> getOneFeedback(@PathVariable Integer userFeedbackCount) {
fixed

2023-08-30 19:18 UTC, Pvs11 commented on src/main/java/team/exlab/ecohub/feedback/controller/AdminFeedbackController.java
> +    public AdminFeedbackController(FeedbackServiceImpl service) {
fixed

2023-08-30 19:21 UTC, Pvs11 commented on src/main/java/team/exlab/ecohub/feedback/controller/AdminFeedbackController.java
> +    @GetMapping("/messages")
изначально писал чтобы различать методы юзера и админа, исправил)

2023-08-30 19:23 UTC, Pvs11 commented on src/main/java/team/exlab/ecohub/feedback/controller/AdminFeedbackController.java
> +    public CollectionModel<EntityModel<FeedbackAdminDto>> getAllMessages(@RequestParam(required = false, defaultValue = "DEFAULT") String status,
Верно, оставил дефолт для того чтобы приходили все отзывы независимо от статуса, иначе на фронт придут только те у которых статус OPEN

2023-08-30 19:24 UTC, Pvs11 commented on src/main/java/team/exlab/ecohub/feedback/model/ResponseStatus.java
> +import java.io.Serializable;
круто! не знал что можно одним махом))

2023-08-30 19:29 UTC, Pvs11 commented on src/main/java/team/exlab/ecohub/feedback/service/FeedbackServiceImpl.java
> +        } else if (Objects.equals(status.name(), "DEFAULT") && !Objects.equals(topic.name(), "DEFAULT")) {
может, если админ не передает параметров, то это его дефолтное значение чтобы показать все отзывы с любым статусом

2023-08-30 19:30 UTC, Pvs11 commented on src/main/java/team/exlab/ecohub/feedback/service/FeedbackServiceImpl.java
> +        Feedback feedback = feedbackRepository.findById(feedbackId).orElseThrow();
fixed

2023-08-30 19:39 UTC, Pvs11 commented on src/main/java/team/exlab/ecohub/feedback/service/FeedbackServiceImpl.java
> +        String responseContent = feedbackAdminDto.getResponseContent();
fixed

2023-08-30 19:39 UTC, Pvs11 commented on src/main/java/team/exlab/ecohub/feedback/controller/AdminFeedbackController.java
> +    public EntityModel<FeedbackAdminDto> makeResponse(@RequestBody FeedbackAdminDto feedbackAdminDto, @PathVariable Long id) {
fixed

2023-08-30 19:41 UTC, Pvs11 commented on src/main/java/team/exlab/ecohub/feedback/model/ResponseStatus.java
> +    OPEN, CLOSED, IN_PROGRESS, DEFAULT
fixed

2023-08-30 19:41 UTC, Pvs11 commented on src/main/resources/schema.sql
> +    FEEDBACKS_USERS,
fixed

2023-08-31 18:23 UTC, Pvs11 commented on src/main/java/team/exlab/ecohub/feedback/service/FeedbackServiceImpl.java
> +    public EntityModel<FeedbackAdminDto> createResponseToFeedback(FeedbackAdminDto feedbackAdminDto, Long feedbackId) {
думал что этот id передается как параметр в запросе, поэтому проще уже готовый использовать вместо того чтобы доставать из ДТО. Надо обсудить еще

2023-08-31 18:23 UTC, Pvs11 commented on src/main/java/team/exlab/ecohub/feedback/model/Feedback.java
> +    @Column(name = "id")
Для наглядности оставляю

2023-09-11 15:01 UTC, closed without merging