News
exlab-ecohub/ecohub-main pull request #7
Opened 2024-04-08 19:35 UTC by Pvs11

2024-04-17 17:58 UTC, nikitabulak requested changes

2024-04-17 17:58 UTC, nikitabulak commented on src/main/java/team/exlab/ecohub/news/controller/AttachmentsController.java
> +    @GetMapping(value = "/E:/Git-projects/ecohub-main/files/news/images/**", produces = MediaType.IMAGE_JPEG_VALUE)
Директорию хранения не стоит хардкодить. Лучше передавать её на этапе запуска сервиса. Посмотри, как определен, например, параметр spring.datasource.url в application.properties и в application-dev.properties

2024-04-17 17:58 UTC, nikitabulak commented on src/main/java/team/exlab/ecohub/news/dto/NewsItemDto.java
> +	private String publicationDate;
Почему строка, а не LocalDateTime?

2024-04-17 17:58 UTC, nikitabulak commented on src/main/java/team/exlab/ecohub/news/dto/NewsItemDto.java
> +	private Set<Attachment> imageAttachment;
Почему Set? Предполагается возможность хранения нескольких картинок? Нигде дальше не используется

2024-04-17 17:58 UTC, nikitabulak commented on src/main/java/team/exlab/ecohub/news/validation/ImageFileValidator.java
> +		} else return true;
Минутка "Вдруг ты не знал, что так можно". 
При желании избавиться от "if (contentType != null)" можно весь if-else сокращать до 
return contentType != null && (contentType.equals("image/png") || contentType.equals("multipartFile/jpg") || contentType.equals("image/jpeg") || contentType.equals("image/gif"));

В случае, если contentType таки будет равен null, contentType.equals() не выбросит NullPointerException, т.к. не будет выполнен. Если первый аргумент оператора && оказывается равен false, то состояние второго аргумента не проверяется)

2024-04-17 17:58 UTC, nikitabulak commented on src/main/java/team/exlab/ecohub/news/validation/ImageFileValidator.java
> +	private boolean isSupportedDimensions(MultipartFile multipartFile) {
Может, isSupportedResolutions больше подходит?)

2024-04-17 17:58 UTC, nikitabulak commented on src/main/java/team/exlab/ecohub/news/validation/ImageFileValidator.java
> +		} else return true;
Возвращение true при неизвестном/отсутствующем contentType как будто противоречит смыслу, вложенному в название метода

2024-04-17 17:58 UTC, nikitabulak commented on src/main/java/team/exlab/ecohub/news/validation/ImageFileValidator.java
> +		} else return true;
Возвращение true при пустом multipartFile как будто противоречит смыслу, вложенному в название метода

2024-04-17 17:58 UTC, nikitabulak commented on src/main/resources/application.properties
> +resources.images-directory=user.dir
Директорию хранения не стоит хардкодить. Лучше передавать её на этапе запуска сервиса. Посмотри, как определен, например, параметр spring.datasource.url в application.properties и в application-dev.properties

2024-04-17 17:58 UTC, nikitabulak commented on src/main/java/team/exlab/ecohub/news/service/NewsItemServiceImpl.java
> +			String fileName = "image_" + UUID.randomUUID() + "_" + imageAttachment.getOriginalFilename();
Может UUID в конец названия? При необходимости будет проще искать по исходному имени файла

2024-04-17 17:58 UTC, nikitabulak commented on src/main/java/team/exlab/ecohub/news/service/NewsItemServiceImpl.java
> +			return null;
В идеале возвращать не null, а оборачивать в Optional

2024-04-17 17:58 UTC, nikitabulak commented on src/main/java/team/exlab/ecohub/news/service/NewsItemServiceImpl.java
> +		deleteImage(newsItemToEdit.getImageAttachment());
Если в новости не редактируется картинка, а редактируется только текст/заголовок - новость лишится картинки)

2024-04-17 17:58 UTC, nikitabulak commented on src/main/java/team/exlab/ecohub/news/controller/NewsController.java
> +	public List<NewsItemDto> getAllNews() {
Нужна пагинация

2024-04-17 17:58 UTC, nikitabulak commented on src/main/java/team/exlab/ecohub/news/service/NewsItemServiceImpl.java
> +		return newsItemRepository.findAll().stream().map(NewsItemMapper::toDto).collect(Collectors.toList());
Помнишь пагинацию? Она нужна

2024-04-17 17:58 UTC, nikitabulak commented on src/main/java/team/exlab/ecohub/news/StorageConfigurationProperties.java
> +	private String imagesDirectory;
В чем преиумщества именно такой передачи директории? Почему именно через ConfigurationProperties?

2024-04-17 20:14 UTC, Pvs11 commented on src/main/java/team/exlab/ecohub/news/dto/NewsItemDto.java
> +	private Set<Attachment> imageAttachment;
Да, только поэтому оставил, будет возможность добавить небольшую галерею. И дополнительно вроде бы джава пишет ошибку когда пытаешься указать в классе помеченном @Entity объект типа Attachment

2024-04-17 20:20 UTC, Pvs11 commented on src/main/java/team/exlab/ecohub/news/validation/ImageFileValidator.java
> +		} else return true;
При такой замене джава мне начинает подсказывать что может быть выброшен эксепшн.

2024-04-17 20:21 UTC, Pvs11 commented on src/main/java/team/exlab/ecohub/news/validation/ImageFileValidator.java
> +	private boolean isSupportedDimensions(MultipartFile multipartFile) {
Вполне может быть) мне не принципиально)) исправил)

2024-04-30 18:46 UTC, Pvs11 commented on src/main/java/team/exlab/ecohub/news/dto/NewsItemDto.java
> +	private String publicationDate;
fixed

2024-04-30 18:51 UTC, Pvs11 commented on src/main/java/team/exlab/ecohub/news/dto/NewsItemDto.java
> +	private Set<Attachment> imageAttachment;
В случае если в классе NewsItem убрать Set то джава ругается на то что many to many attribute type should be a container. Пока думаю лучше оставить как есть. В крайнем случае можно просто будет указывать синглтон и больше одного атачмента не получиться вложить.

2024-04-30 18:54 UTC, Pvs11 commented on src/main/java/team/exlab/ecohub/news/validation/ImageFileValidator.java
> +		} else return true;
Исправил, надо было правильно сгрупировать)

2024-04-30 19:04 UTC, Pvs11 commented on src/main/java/team/exlab/ecohub/news/validation/ImageFileValidator.java
> +		} else return true;
fixed

2024-04-30 19:22 UTC, Pvs11 commented on src/main/java/team/exlab/ecohub/news/validation/ImageFileValidator.java
> +		} else return true;
Получается если изображение не передается то валидация не дает ошибку по размеру изображения.
Название возможно не совсем точное, но логика работает как по мне верно, без противоречий, название поменял.

2024-05-01 19:17 UTC, Pvs11 commented on src/main/resources/application.properties
> +resources.images-directory=user.dir
Пофиксил, думаю все окей, но лучше пересмотреть.

2024-05-01 19:47 UTC, Pvs11 commented on src/main/java/team/exlab/ecohub/news/service/NewsItemServiceImpl.java
> +			String fileName = "image_" + UUID.randomUUID() + "_" + imageAttachment.getOriginalFilename();
Согласен, пофиксил.

2024-05-01 20:14 UTC, Pvs11 commented on src/main/java/team/exlab/ecohub/news/service/NewsItemServiceImpl.java
> +			return null;
fixed

2024-05-01 20:40 UTC, Pvs11 commented on src/main/java/team/exlab/ecohub/news/service/NewsItemServiceImpl.java
> +		deleteImage(newsItemToEdit.getImageAttachment());
fixed

2024-05-02 13:40 UTC, Pvs11 commented on src/main/java/team/exlab/ecohub/news/StorageConfigurationProperties.java
> +	private String imagesDirectory;
Преимуществ нет, просто искал рабочий вариант. Аннотация Value так почему-то и не заработала, использовал вариант через экземпляр Environment, код сократился.

2024-05-02 14:37 UTC, Pvs11 commented on src/main/java/team/exlab/ecohub/news/controller/NewsController.java
> +	public List<NewsItemDto> getAllNews() {
добавил

2024-05-02 14:37 UTC, Pvs11 commented on src/main/java/team/exlab/ecohub/news/service/NewsItemServiceImpl.java
> +		return newsItemRepository.findAll().stream().map(NewsItemMapper::toDto).collect(Collectors.toList());
добавил

2024-07-07 17:33 UTC, merged